name: svuce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # for os-specific path directory
  path_provider:

  # Local Database
  hive:
  shared_preferences:

  # state management
  stacked: ^2.1.6

  # third party usable services
  stacked_services: ^0.8.6

  # inversion of control
  injectable:
  get_it:
  flutter_hooks:

  # firebase
  cloud_firestore: ^2.2.0
  firebase_auth: ^1.2.0
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  firebase_core: ^1.2.0
  firebase_analytics:

  #notifications
  onesignal_flutter:

  #Animations
  animations:
  simple_animations:

  # icons
  eva_icons_flutter: ^3.0.0
  flutter_icons: ^1.1.0

  # main utilities
  image_picker: ^0.7.5+2
  observable_ish:
  flutter_cache_manager:
  logger:
  http:
  table_calendar: ^3.0.0
  firebase_dynamic_links: ^2.0.4
  share_plus:
  fl_chart:
  excel:
  dotted_border:
  file_picker:
  permission_handler:
  flutter_colorpicker:
  flutter_local_notifications:
  add_2_calendar:
  markdown_widget:
  carousel_slider:
  flutter_native_timezone:
  timezone:
dev_dependencies:
  flutter_test:
    sdk: flutter

  # generators
  hive_generator:
  build_runner: null
  auto_route_generator: null
  injectable_generator: null

  # for models
  freezed: ^0.12.7
  json_serializable:

  # testing
  mockito: null
  cloud_firestore_mocks: null
  flutter_launcher_icons:
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/images/

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
