name: svuce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # For os-specific path directory
  path_provider: ^1.6.7
  # Hive
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  http: ^0.12.1

  # state management
  stacked: ^1.4.2
  # third party usable services
  stacked_services: ^0.2.2
  # navigation
  auto_route:
  # inversion of control
  get_it:
  injectable:
  # firebase
  cloud_firestore: ^0.13.4+2
  firebase_auth:
  firebase_messaging: ^6.0.13
  firebase_storage: ^3.1.1
  #icons
  eva_icons_flutter: ^2.0.0
  flutter_icons: ^1.0.0+1
  # utitily to pick images
  image_picker: ^0.6.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generators
  hive_generator: ^0.5.1
  build_runner: 
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/hexagon_pattern.jpg
    - assets/illustrations/asteroid_pattern.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400

    - family: Worksans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
