name: svuce_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  stacked: ^1.2.2
  # third party usable services
  stacked_services:
  # navigation
  auto_route:
  # inversion of control
  get_it:
  injectable:
  # firebase
  cloud_firestore: ^0.13.4+2
  firebase_auth:
  firebase_messaging: ^6.0.13
  #icons
  eva_icons_flutter: ^2.0.0
  flutter_icons: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  #generators
  build_runner:
  auto_route_generator:
  injectable_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/hexagon_pattern.jpg
    - assets/illustrations/asteroid_pattern.png

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400

    - family: Worksans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
